[package]
name = "errornowatcher"
version = "0.2.0"
edition = "2024"

[profile.dev]
opt-level = 1

[profile.dev.package."*"]
opt-level = 3

[profile.release]
codegen-units = 1
lto = true
panic = "abort"
strip = true

[dependencies]
anyhow = "1"
azalea = { git = "https://github.com/azalea-rs/azalea.git" }
clap = { version = "4", features = ["derive"] }
futures = "0"
mlua = { version = "0", features = ["async", "luau", "send"] }
parking_lot = { version = "0" }
tokio = { version = "1", features = ["macros"] }
