[package]
name = "errornowatcher"
version = "0.1.0"
edition = "2021"

[dependencies]
azalea = "0.5.0"
azalea-protocol = "0.5.0"
azalea-block = "0.5.0"
azalea-core = "0.5.0"
toml = "0.5.10"
serde = { version = "1.0", features = ["derive"] }
tokio = { version = "1.24.2", features = ["macros", "rt-multi-thread"] }
anyhow = "1.0.68"
colored = "2.0.0"
chrono = "0.4.23"
strum = "0.24.1"
strum_macros = "0.24.1"
async-recursion = "1.0.0"
rand = "0.8.5"
matrix-sdk = "0.6.2"
